### ISSUE TITLE
Exception: AuthException(code=5, alertMessage='[HUMAN_VERIFICATION_REQUIRED] [HUMAN_VERIFICATION_REQUIRED] Required to resolve captcha.'

### ISSUE THREAD

**Issue by vickysaputraa** [LRTT/LINEREGISTER#5] opened 2020-05-25 02:27 UTC
can you help solve it?

**Comment by LRTT** [comment] 2020-05-25 06:14
Duplicate of #4

**Closed by LRTT** 2020-05-25 06:14 UTC
